### PR TITLE
fix: apt cache performance

### LINKED ISSUE #103: Verifying packages is slow
We tried this action to improve our apt install performance in our workflows and once cached it was often actually slower than just performing the `apt-get install`.

I did a bit of digging and the main delay was "Verifying packages" process which is taking about 0.7s per package listed.

Testing locally `apt-cache show ${package}` is ~40ms where as on github is ~700ms.

Given this and the current flow we could be spending ~1.4s per package just calling `apt-cache show`.

### PR DESCRIPTION
**Pull request by stevenh**
Use a single call to apt-cache to reduce the time needed to lookup package versions.

Also:
* Added millisecond details to log timing so slow operations can be more easily identified.
* Perform apt update before determining package versions.

Fixes #103

### CODE REVIEW

**Comment by stevenh** [comment]
In a simple test case with 7 packages this reduced the processing time from 17s to 4s for the cached case.

File: install_and_cache_pkgs.sh [hunk 1]
```diff
@@ -18,28 +18,6 @@ cache_dir="${1}"
 # List of the packages to use.
 input_packages="${@:3}"
 
-# Trim commas, excess spaces, sort, and version syntax.
```
Comment (awalsh128) [inline install_and_cache_pkgs.sh:21]: Can we retain the comments here?

File: lib.sh [hunk 2]
```diff
@@ -81,7 +81,9 @@ function get_package_name_ver {
   IFS="${ORIG_IFS}"
   # If version not found in the fully qualified package value.
   if test -z "${ver}"; then
-    ver="$(grep "Version:" <<< "$(apt-cache show ${name})" | awk '{print $2}')"
+    # This is a fallback and should not be used any more as its slow.
+    log_err "Unexpected version resolution for package '${name}'..."
```
Comment (awalsh128) [inline lib.sh:85]: Ellipses is usually used to indicate a continuing operation.

File: lib.sh [hunk 3]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
-  local stripped=$(echo "${1}" | sed 's/[,\]/ /g')
-  # Remove extraneous spaces at the middle, beginning, and end.
-  local trimmed="$(\
-    echo "${stripped}" \
-    | sed 's/\s\+/ /g; s/^\s\+//g; s/\s\+$//g')"
-  echo ${trimmed} | tr ' ' '\n' | sort | tr '\n' ' '
+  # Remove commas, and block scalar folded backslashes,
+  # extraneous spaces at the middle, beginning and end
+  # then sort.
+  packages=$(echo "${1}" | \
```
Comment (awalsh128) [inline lib.sh:102]: nit: Can you start each line with a pipe to keep the syntax consistent?

File: lib.sh [hunk 4]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
+    sed 's/[,\]/ /g; s/\s\+/ /g; s/^\s\+//g; s/\s\+$//g' | \
+    sort -t' ')
+
+  # Validate package names and get versions.
+  log_err "resolving package versions..."
```
Comment (awalsh128) [inline lib.sh:107]: This should be log I believe. Also upper case R.

File: lib.sh [hunk 5]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
+  data=$(apt-cache --quiet=0 --no-all-versions show ${packages} 2>&1 | \
+    grep -E '^(Package|Version|N):')
+  log_err "resolved"
+
+  local ORIG_IFS="${IFS}"
+  IFS=$'\n'
+  declare -A missing
+  local package_versions=''
+  local pkg='' sep=''
```
Comment (awalsh128) [inline lib.sh:116]: nit: For consistency, use non-abbreviated names.

File: lib.sh [hunk 6]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
+  for v in ${data}; do
```
Comment (awalsh128) [inline lib.sh:117]: Can we use a more descriptive name? Also, the iterative variable can be something like pair or key_value?

File: lib.sh [hunk 7]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
+      Package)
+        pkg=$val
+        ;;
+      Version)
+        package_versions="${package_versions}${sep}"${pkg}=${val}""
+        sep=' '
+        ;;
+      N)
+        # Warning messages.
+        case $val in
```
Comment (awalsh128) [inline lib.sh:131]: Curious, why use a single case block?

File: lib.sh [hunk 8]
```diff
@@ -91,16 +93,63 @@ function get_package_name_ver {
...
+          'Unable to locate package '*)
+            pkg="${val#'Unable to locate package '}"
+            # Avoid duplicate messages.
+            if [ -z "${missing[$pkg]}" ]; then
+              pkg="${val#'Unable to locate package '}"
```
Comment (awalsh128) [inline lib.sh:136]: log_err?

**Review by awalsh128 — CHANGES_REQUESTED** [review]
Thank you so much for this PR. Added some minor feedback.

Can you redo the PR into the dev branch? That way I can run it against the CI.

File: lib.sh (hunk 4 above)
Comment (stevenh) [reply lib.sh:107]: This can't be a log as it would interfere with the returned value unfortunately.

File: install_and_cache_pkgs.sh (hunk 1 above)
Comment (stevenh) [reply install_and_cache_pkgs.sh:21]: The reason I removed the comments they were incorrect and the function defines what it does.

The impact of this is you either get code churn when what it does changes or even worse incorrect comments when the function changes but all uses aren't update.

This is what happened when the the syntax was changed from colon to equals, making this comment incorrect.

Thoughts?

File: lib.sh (hunk 7 above)
Comment (stevenh) [reply lib.sh:131]: `case` statements support patterns by default, `if` needs more work and if we want to handle more cases in the future easy to add.

I believe the following would be equivalent `if` statement
```bash
if [[ $value =~ "Unable to locate package *" ]]; then
```

Thoughts?

**Comment by stevenh** [comment]
Quick nudge to see if we can get this one in @awalsh128

**Comment by bonlime** [comment]
@awalsh128 what stops this from being merged?

**Comment by richarddd** [comment]
Any update?

**Review by awalsh128 — APPROVED** [review]

**Comment by awalsh128** [comment]
Sorry for the really long wait. It has now been merged into master. I'll do a release today or tomorrow.

**Comment by awalsh128** [comment]
This is now included in release [v1.3.1](https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.3.1).

Although it looks like it is causing 2 regressions on the CI.

* https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/6697244906/job/18196709301
* https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/6697244906/job/18196712208

The most critical is the multiline block one. If I can't resolve in a couple of days I will need to pull the change for now. Could you help diagnose the issue introduced with the latest change (verified it is in this PR)?

**Comment by stevenh** [comment]
> This is now included in release [v1.3.1](https://github.com/awalsh128/cache-apt-pkgs-action/releases/tag/v1.3.1).
> 
> Although it looks like it is causing 2 regressions on the CI.
> 
> * https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/6697244906/job/18196709301
> * https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/6697244906/job/18196712208
> 
> The most critical is the multiline block one. If I can't resolve in a couple of days I will need to pull the change for now. Could you help diagnose the issue introduced with the latest change (verified it is in this PR)?

Could you describe how I can validate this, so I can investigate @awalsh128 ?

**Comment by awalsh128** [comment]
The easiest to tackle is https://github.com/awalsh128/cache-apt-pkgs-action-ci/actions/runs/6697244906/job/18196712208 which tests that two package lists of different order should be the same in terms of a cache hit.

I think the issue here is that the returned normalized package list no longer sorts. Below is the difference now between the pre-hashed value.

```
xdot=1.2-2 rolldice=1.16-1build1 @ 6697244906-1-standard_workflow 1
rolldice=1.16-1build1 xdot=1.2-2 @ 6697244906-1-standard_workflow 1
```

BTW, received a report today where it is failing on the function. https://github.com/awalsh128/cache-apt-pkgs-action/issues/116
Isn't open source fun? 😆
